---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-0b500ef59d8335eee  # Redhat
      keypair: AWS-demo # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "AKIAJ3NWM67AGFLGOVJA"
         aws_secret_key: "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"
         group: launch-wizard-4  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "Demo"
         instance_tags:
            Name: "Demo"
         vpc_subnet_id: "subnet-1d875951"
         assign_public_ip: yes
      register: ec2

    - debug:
        msg: "{{ item['private_ip'] }}"
      with_items: "{{ ec2.instances }}"

    - name: wait for ssh port
      wait_for: port-22 host-"{{ item['private_ip'] }}" timeout-120 state=started
      with_items: "{{ ec2.instances }}" 

    - name: create a new inventory
      add_host:
        host_name: "{{ item['private_ip'] }}"
        ansible_user: ec2-user
        ansible_ssh_key: /root/.ssh/key.pem
        groups: webserver
        with_items: "{{ ec2.instances }}"
    - set_fact: ip_list= "[]"
